inhibit_all_warnings!
pod 'AFNetworking', '~> 2.6.0'
pod 'SDWebImage', '~> 3.7.3'
pod 'MBProgressHUD', '~> 0.9.1'
pod 'FinalStarRatingBar', '~> 0.0.2'
pod 'MagicalRecord', '~> 2.3.0'
pod 'DJWStarRatingView', '~> 0.0.4'
pod 'UMengAnalytics', '~> 3.6.4'
pod 'AMap2DMap', '~> 3.1.0'
pod 'AMapSearch', '~> 3.0.1'
pod 'UMengFeedback', '~> 2.3.4'


